### ISSUE TITLE
Suggested adjustment to the API

### ISSUE THREAD

**Issue by tracker1** [gigantz/reactend-express#1]
Interresting...  

The following might be slightly cleaner:

```
import {App, Static, Router, Get, Post, Put, Delete, Patch} from 'react-express';
```

Would also suggest passing a renderer function for the content...

ex:
```
   <Get path="/" content={() => <HomePage />} />
```

So that rendering of HomePage, etc is deferred until demanded.

**Comment by tracker1** [comment]
Should probably support async functions for content, so that if a thenable is returned, that it awaits the result, then sends the response... this way you can add async handlers for API requests, etc.

**Comment by gigantz** [comment]
Thanks for this awesome idea about components. 
``` js
import {App, Static, Router, Get, Post, Put, Delete, Patch} from 'react-express';
```
I'm gonna add them. Sadly `react-express` has taken, that's why I named it `react-xpress` :) 

Please have a look [here](https://github.com/gigantz/react-xpress/tree/master/examples/advanced)
It's a kinda "advanced" example, so you can use async handler.

<br />
I have an idea to enlarge component based structure. Something like this

```js
<Get path="/not-found">
  <Res.Status code={404} />
  <Res.Content>Page is not found</Res.Content>
</Get>
```

**Comment by gigantz** [comment]
@tracker1 updated
